spring:
  application:
    name: fitness-club
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/fitness-club
    username: fitness-club
    password: fitness-club
  jpa:
    hibernate:
      ddl-auto: update

# App Properties
app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000
